name: Deploy Tich to Amazon EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make Directory for deliver
        run: mkdir -p tich-deploy

      - name: Copy shell script
        run: cp scripts/*.sh tich-deploy/

      - name: Copy appspec
        run: cp appspec.yml tich-deploy/

      - name: Copy jar
        run: cp build/libs/*.jar tich-deploy/

      - name: Make zip file
        run: zip -r tich-deploy.zip tich-deploy/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp tich-deploy.zip s3://mash-up-tich-build/Tich-Backend/tich-deploy.zip --region ap-northeast-2

      - name: Code Deploy
        run: aws deploy create-deployment --application-name tich-app --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name tich --s3-location bucket=mash-up-tich-build,bundleType=zip,key=Tich-Backend/tich-deploy.zip
